version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "hourly"
      time: "12:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    target-branch: master
    labels:
      - dependencies-back
      - dependabot
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "12:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    target-branch: master
    labels:
      - dependencies-front
      - dependabot
